### ISSUE TITLE
Merge into mainline CMS

### ISSUE THREAD

**Issue by msoos** [Storyyeller/cryptominisat-rs#1]
Hey! This is cool! I would be interested if you could merge this into mainline CMS :) I saw this on reddit by accident, you should definitely have asked me to do it! It would be nice. Also, currently this is taking 5.0.1, but 5.6.3 is so much better :) But best would be to merge into mainline. Could you try to make a pull request?

Thanks!

**Comment by Storyyeller** [comment]
I didn't realize you had updated CMS again. I'll look into this when I have time.

**Comment by msoos** [comment]
Interface stayed the same so it should just work out of the box :)

**Comment by Storyyeller** [comment]
Ok, I updated it to v5.6.3 and published a new version. 

As far as merging this upstream, I agree that it is the best option, I'm just not sure how you would want the files arranged. What do you suggest?

**Comment by Storyyeller** [comment]
I created a PR (https://github.com/msoos/cryptominisat/pull/505). I'm not sure why there are submodule changes in there but hopefully I did it right.
