### ISSUE TITLE
Questions about how best to do rust bindings

### ISSUE THREAD

**Issue by msoos** [Storyyeller/cryptominisat-rs#2]
Hi,

I have a question about how to best do rust bindings. It seems to me that the "rust" subdirectory in CryptoMiniSat is basically not the best idea, and instead, this kind of repo that you have here is the best way forward. In that spirit, I have cloned it (actually, cloned a version of it that was improved by https://github.com/ltentrup (he uses your&my work in: https://github.com/ltentrup/caqe ) This now improved (also by me) repo is now at: https://github.com/msoos/cryptominisat-rs

Do you think I can delete the "rust" subdirectory of CryptoMiniSat and just redirect people to the repo at https://github.com/msoos/cryptominisat-rs ? Because it seems that this repo is easier to use in rust. For example, in caqe:

https://github.com/msoos/caqe/blob/master/Cargo.toml#L8
https://github.com/msoos/caqe/blob/master/Cargo.lock#L67

Which seems super-easy to me. What do you think?

Thanks,

Mate

**Comment by Storyyeller** [comment]
I don't have any particular opinion on the matter.

**Comment by msoos** [comment]
Oh, cool, I'll move to the repo-based one then :) Thanks!
